cache:
  directories:
  - $HOME/.m2
language: java
jdk:
- oraclejdk8
script: ./build.sh
after_success:
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/pubring.gpg.enc -out $GPG_DIR/pubring.gpg -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/secring.gpg.enc -out $GPG_DIR/secring.gpg -d
- $GPG_DIR/publish.sh
env:
  global:
  - GPG_DIR="`pwd`/deploy"
  - secure: m8lLBPDnAlaYo7KbfJynRMZ5qbBh38rmEBX/NHLNXl8OveqDo0/C7lYvICKnRjbncP4lIYl3I/l5O2RdScyW83qAmhffI05b4mawTIyq4RegowkWSprr53OMy8yvPo8u0UheH2188rH6fkROroS/L1yTod22jBHC1IgEiSinsgR+YRzu5pg1mrV9R4bV5mWHBpX5opQJteMXA0ved8CNwkOmf61F2s3IL3Q+yLuDynui4LH3AyMW5XpksgiTy+5evmOCc9h9uWrIlIyr95kjmLUz4HQviCo3tuqXUyB2QNEViQY8I7WN3l6qsxXlQW8DdXqUgu+SMzN08uzw5kTlA9ZSkyIw0cu6DKpRkmH/ILaW2syxsECkK/YZZ26gicwj/kfUB1C5kR9pXHpFRlfJvw5IowlHeQaL5ob5CLtiyQFKJOLj03OWmQepU8jOz1WuCruKVsyeNg3NvbGzuMXQSB4ETgwzYlwqOhfY0tBa5cEoV9V265vxxNLHoFGXmNJn3ioRug8fxJAxjXQaeVGqNbSvmmOV2f0hns9daL6UyAQS5OvuXArzQmxAzRTa2W3AX25j8ka+FY/rbSzPrAda1XCKNdZGqyG85ikpw/gwKByiA3/kaWp0kfJV6u4ylFb8R31HHTvdH3mSYZ68RF8HE+wL13Zt+nWI6HuAgmK7M/8=
